//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentYouRide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentYouRideDBEntities : DbContext
    {
        public RentYouRideDBEntities()
            : base("name=RentYouRideDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Car> tbl_Car { get; set; }
        public virtual DbSet<tbl_CarBodyType> tbl_CarBodyType { get; set; }
        public virtual DbSet<tbl_CarMake> tbl_CarMake { get; set; }
        public virtual DbSet<tbl_Driver> tbl_Driver { get; set; }
        public virtual DbSet<tbl_Inspector> tbl_Inspector { get; set; }
        public virtual DbSet<tbl_Rental> tbl_Rental { get; set; }
        public virtual DbSet<tbl_Return> tbl_Return { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
