//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentYouRide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Car
    {
        public int ID_Car { get; set; }
        public string CarNo { get; set; }
        public string CarMake { get; set; }
        public string Model { get; set; }
        public string BodyType { get; set; }
        public int Kilometers_Travelled { get; set; }
        public int Service_Kilometers { get; set; }
        public string Available { get; set; }
    }
}
